/*
  Register definitions for slave core: External Flash Update

  * File           : wb_FlashUpdate.c
  * Author         : auto-generated by wbgen2 from gen_FlashUpdate.wb
  * Created        : 12/05/12 09:48:26
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE gen_FlashUpdate.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_GEN_FLASHUPDATE_WB
#define __WBGEN2_REGDEFS_GEN_FLASHUPDATE_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Flash parameters */

/* definitions for field: parameter data in reg: Flash parameters */
#define WBFLASH_PARAMS_DATA_MASK              WBGEN2_GEN_MASK(0, 24)
#define WBFLASH_PARAMS_DATA_SHIFT             0
#define WBFLASH_PARAMS_DATA_W(value)          WBGEN2_GEN_WRITE(value, 0, 24)
#define WBFLASH_PARAMS_DATA_R(reg)            WBGEN2_GEN_READ(reg, 0, 24)

/* definitions for field: parameter address in reg: Flash parameters */
#define WBFLASH_PARAMS_ADDRESS_MASK           WBGEN2_GEN_MASK(24, 3)
#define WBFLASH_PARAMS_ADDRESS_SHIFT          24
#define WBFLASH_PARAMS_ADDRESS_W(value)       WBGEN2_GEN_WRITE(value, 24, 3)
#define WBFLASH_PARAMS_ADDRESS_R(reg)         WBGEN2_GEN_READ(reg, 24, 3)

/* definitions for field: parameter write in reg: Flash parameters */
#define WBFLASH_PARAMS_WRITE_MASK             WBGEN2_GEN_MASK(27, 1)
#define WBFLASH_PARAMS_WRITE_SHIFT            27
#define WBFLASH_PARAMS_WRITE_W(value)         WBGEN2_GEN_WRITE(value, 27, 1)
#define WBFLASH_PARAMS_WRITE_R(reg)           WBGEN2_GEN_READ(reg, 27, 1)

/* definitions for field: parameter read request in reg: Flash parameters */
#define WBFLASH_PARAMS_REQUEST_MASK           WBGEN2_GEN_MASK(28, 1)
#define WBFLASH_PARAMS_REQUEST_SHIFT          28
#define WBFLASH_PARAMS_REQUEST_W(value)       WBGEN2_GEN_WRITE(value, 28, 1)
#define WBFLASH_PARAMS_REQUEST_R(reg)         WBGEN2_GEN_READ(reg, 28, 1)

/* definitions for field: start reconfiguration in reg: Flash parameters */
#define WBFLASH_PARAMS_RECONF_MASK            WBGEN2_GEN_MASK(29, 3)
#define WBFLASH_PARAMS_RECONF_SHIFT           29
#define WBFLASH_PARAMS_RECONF_W(value)        WBGEN2_GEN_WRITE(value, 29, 3)
#define WBFLASH_PARAMS_RECONF_R(reg)          WBGEN2_GEN_READ(reg, 29, 3)

/* definitions for register: Flash parameters read */

/* definitions for field: data read in reg: Flash parameters read */
#define WBFLASH_PARAMS_READ_DATA_MASK         WBGEN2_GEN_MASK(0, 24)
#define WBFLASH_PARAMS_READ_DATA_SHIFT        0
#define WBFLASH_PARAMS_READ_DATA_W(value)     WBGEN2_GEN_WRITE(value, 0, 24)
#define WBFLASH_PARAMS_READ_DATA_R(reg)       WBGEN2_GEN_READ(reg, 0, 24)

/* definitions for field: addres read in reg: Flash parameters read */
#define WBFLASH_PARAMS_READ_ADDRESS_MASK      WBGEN2_GEN_MASK(24, 3)
#define WBFLASH_PARAMS_READ_ADDRESS_SHIFT     24
#define WBFLASH_PARAMS_READ_ADDRESS_W(value)  WBGEN2_GEN_WRITE(value, 24, 3)
#define WBFLASH_PARAMS_READ_ADDRESS_R(reg)    WBGEN2_GEN_READ(reg, 24, 3)

/* definitions for field: configuration busy in reg: Flash parameters read */
#define WBFLASH_PARAMS_READ_BUSY_MASK         WBGEN2_GEN_MASK(27, 1)
#define WBFLASH_PARAMS_READ_BUSY_SHIFT        27
#define WBFLASH_PARAMS_READ_BUSY_W(value)     WBGEN2_GEN_WRITE(value, 27, 1)
#define WBFLASH_PARAMS_READ_BUSY_R(reg)       WBGEN2_GEN_READ(reg, 27, 1)

/* definitions for field: configuration data error in reg: Flash parameters read */
#define WBFLASH_PARAMS_READ_ERROR_MASK        WBGEN2_GEN_MASK(28, 1)
#define WBFLASH_PARAMS_READ_ERROR_SHIFT       28
#define WBFLASH_PARAMS_READ_ERROR_W(value)    WBGEN2_GEN_WRITE(value, 28, 1)
#define WBFLASH_PARAMS_READ_ERROR_R(reg)      WBGEN2_GEN_READ(reg, 28, 1)

/* definitions for field: configuration write error in reg: Flash parameters read */
#define WBFLASH_PARAMS_READ_ILLEGAL_MASK      WBGEN2_GEN_MASK(29, 1)
#define WBFLASH_PARAMS_READ_ILLEGAL_SHIFT     29
#define WBFLASH_PARAMS_READ_ILLEGAL_W(value)  WBGEN2_GEN_WRITE(value, 29, 1)
#define WBFLASH_PARAMS_READ_ILLEGAL_R(reg)    WBGEN2_GEN_READ(reg, 29, 1)

/* definitions for field: illegal flash erase in reg: Flash parameters read */
#define WBFLASH_PARAMS_READ_ERASE_ERROR_MASK  WBGEN2_GEN_MASK(30, 1)
#define WBFLASH_PARAMS_READ_ERASE_ERROR_SHIFT 30
#define WBFLASH_PARAMS_READ_ERASE_ERROR_W(value) WBGEN2_GEN_WRITE(value, 30, 1)
#define WBFLASH_PARAMS_READ_ERASE_ERROR_R(reg) WBGEN2_GEN_READ(reg, 30, 1)

/* definitions for register: Flash data */

/* definitions for field: flash data in reg: Flash data */
#define WBFLASH_FLASH_DATA_DATA_MASK          WBGEN2_GEN_MASK(0, 8)
#define WBFLASH_FLASH_DATA_DATA_SHIFT         0
#define WBFLASH_FLASH_DATA_DATA_W(value)      WBGEN2_GEN_WRITE(value, 0, 8)
#define WBFLASH_FLASH_DATA_DATA_R(reg)        WBGEN2_GEN_READ(reg, 0, 8)

/* definitions for field: flash address in reg: Flash data */
#define WBFLASH_FLASH_DATA_ADDRESS_MASK       WBGEN2_GEN_MASK(8, 24)
#define WBFLASH_FLASH_DATA_ADDRESS_SHIFT      8
#define WBFLASH_FLASH_DATA_ADDRESS_W(value)   WBGEN2_GEN_WRITE(value, 8, 24)
#define WBFLASH_FLASH_DATA_ADDRESS_R(reg)     WBGEN2_GEN_READ(reg, 8, 24)

/* definitions for field: Access to flash, disable in wb_FlashUpdate.vhd in reg: Flash data */
#define WBFLASH_FLASH_DATA_ACCESS_MASK        WBGEN2_GEN_MASK(32, 0)
#define WBFLASH_FLASH_DATA_ACCESS_SHIFT       32
#define WBFLASH_FLASH_DATA_ACCESS_W(value)    WBGEN2_GEN_WRITE(value, 32, 0)
#define WBFLASH_FLASH_DATA_ACCESS_R(reg)      WBGEN2_GEN_READ(reg, 32, 0)

/* definitions for register: Flash read */

/* definitions for field: data from flash in reg: Flash read */
#define WBFLASH_FLASH_READ_DATA_MASK          WBGEN2_GEN_MASK(0, 8)
#define WBFLASH_FLASH_READ_DATA_SHIFT         0
#define WBFLASH_FLASH_READ_DATA_W(value)      WBGEN2_GEN_WRITE(value, 0, 8)
#define WBFLASH_FLASH_READ_DATA_R(reg)        WBGEN2_GEN_READ(reg, 0, 8)

/* definitions for field: data from flash is valid in reg: Flash read */
#define WBFLASH_FLASH_READ_VALID_MASK         WBGEN2_GEN_MASK(8, 1)
#define WBFLASH_FLASH_READ_VALID_SHIFT        8
#define WBFLASH_FLASH_READ_VALID_W(value)     WBGEN2_GEN_WRITE(value, 8, 1)
#define WBFLASH_FLASH_READ_VALID_R(reg)       WBGEN2_GEN_READ(reg, 8, 1)

/* definitions for field: accessing flash is busy in reg: Flash read */
#define WBFLASH_FLASH_READ_BUSY_MASK          WBGEN2_GEN_MASK(9, 1)
#define WBFLASH_FLASH_READ_BUSY_SHIFT         9
#define WBFLASH_FLASH_READ_BUSY_W(value)      WBGEN2_GEN_WRITE(value, 9, 1)
#define WBFLASH_FLASH_READ_BUSY_R(reg)        WBGEN2_GEN_READ(reg, 9, 1)

/* definitions for field: error accessing flash in reg: Flash read */
#define WBFLASH_FLASH_READ_ERROR_MASK         WBGEN2_GEN_MASK(10, 1)
#define WBFLASH_FLASH_READ_ERROR_SHIFT        10
#define WBFLASH_FLASH_READ_ERROR_W(value)     WBGEN2_GEN_WRITE(value, 10, 1)
#define WBFLASH_FLASH_READ_ERROR_R(reg)       WBGEN2_GEN_READ(reg, 10, 1)

/* definitions for register: Flash access */

/* definitions for field: Enable data access in reg: Flash access */
#define WBFLASH_FLASH_ACCESS_ENABLE_MASK      WBGEN2_GEN_MASK(0, 1)
#define WBFLASH_FLASH_ACCESS_ENABLE_SHIFT     0
#define WBFLASH_FLASH_ACCESS_ENABLE_W(value)  WBGEN2_GEN_WRITE(value, 0, 1)
#define WBFLASH_FLASH_ACCESS_ENABLE_R(reg)    WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: Enable reading from flash in reg: Flash access */
#define WBFLASH_FLASH_ACCESS_READ_ENABLE_MASK WBGEN2_GEN_MASK(1, 1)
#define WBFLASH_FLASH_ACCESS_READ_ENABLE_SHIFT 1
#define WBFLASH_FLASH_ACCESS_READ_ENABLE_W(value) WBGEN2_GEN_WRITE(value, 1, 1)
#define WBFLASH_FLASH_ACCESS_READ_ENABLE_R(reg) WBGEN2_GEN_READ(reg, 1, 1)

/* definitions for field: Enable writing to flash in reg: Flash access */
#define WBFLASH_FLASH_ACCESS_WRITE_ENABLE_MASK WBGEN2_GEN_MASK(2, 3)
#define WBFLASH_FLASH_ACCESS_WRITE_ENABLE_SHIFT 2
#define WBFLASH_FLASH_ACCESS_WRITE_ENABLE_W(value) WBGEN2_GEN_WRITE(value, 2, 3)
#define WBFLASH_FLASH_ACCESS_WRITE_ENABLE_R(reg) WBGEN2_GEN_READ(reg, 2, 3)

/* definitions for field: Enable erasing sector in reg: Flash access */
#define WBFLASH_FLASH_ACCESS_ERASE_ENABLE_MASK WBGEN2_GEN_MASK(5, 3)
#define WBFLASH_FLASH_ACCESS_ERASE_ENABLE_SHIFT 5
#define WBFLASH_FLASH_ACCESS_ERASE_ENABLE_W(value) WBGEN2_GEN_WRITE(value, 5, 3)
#define WBFLASH_FLASH_ACCESS_ERASE_ENABLE_R(reg) WBGEN2_GEN_READ(reg, 5, 3)

/* definitions for field: Read ID from flash in reg: Flash access */
#define WBFLASH_FLASH_ACCESS_ID_MASK          WBGEN2_GEN_MASK(8, 1)
#define WBFLASH_FLASH_ACCESS_ID_SHIFT         8
#define WBFLASH_FLASH_ACCESS_ID_W(value)      WBGEN2_GEN_WRITE(value, 8, 1)
#define WBFLASH_FLASH_ACCESS_ID_R(reg)        WBGEN2_GEN_READ(reg, 8, 1)

/* definitions for field: Read status form flash in reg: Flash access */
#define WBFLASH_FLASH_ACCESS_STATUS_MASK      WBGEN2_GEN_MASK(9, 1)
#define WBFLASH_FLASH_ACCESS_STATUS_SHIFT     9
#define WBFLASH_FLASH_ACCESS_STATUS_W(value)  WBGEN2_GEN_WRITE(value, 9, 1)
#define WBFLASH_FLASH_ACCESS_STATUS_R(reg)    WBGEN2_GEN_READ(reg, 9, 1)

PACKED struct WBFLASH_WB {
  /* [0x0]: REG Flash parameters */
  uint32_t PARAMS;
  /* [0x4]: REG Flash parameters read */
  uint32_t PARAMS_READ;
  /* [0x8]: REG Flash data */
  uint32_t FLASH_DATA;
  /* [0xc]: REG Flash read */
  uint32_t FLASH_READ;
  /* [0x10]: REG Flash access */
  uint32_t FLASH_ACCESS;
};

#endif
